// Generated by CoffeeScript 1.6.1
(function() {
  var Histogram;

  window.Histogram = Histogram = (function() {

    function Histogram(svg) {
      this.svg = d3.select(svg);
    }

    Histogram.prototype.draw = function(capture, palette, interval) {
      var begin, data, duration, end, intervals, rect, scale_x, scale_y, stream, transactions;
      begin = capture.first_packet().timestamp;
      end = capture.last_packet().timestamp;
      duration = end - begin;
      intervals = Math.floor(duration / interval);
      transactions = _.sortBy(capture.transactions(), function(transaction) {
        return palette.color(transaction).toString();
      });
      data = d3.layout.stack()(transactions.map(function(transaction) {
        var traffic, x;
        traffic = (function() {
          var _i, _results;
          _results = [];
          for (x = _i = 0; 0 <= intervals ? _i <= intervals : _i >= intervals; x = 0 <= intervals ? ++_i : --_i) {
            _results.push({
              x: x,
              y: 0
            });
          }
          return _results;
        })();
        transaction.packets_in.forEach(function(packet) {
          return traffic[Math.floor((packet.timestamp - begin) / interval)].y += packet.size;
        });
        traffic.transaction = transaction;
        return traffic;
      }));
      scale_x = d3.scale.linear().range([0, 100]).domain([0, intervals]);
      scale_y = d3.scale.linear().range([0, 90]).domain([
        0, d3.max(data[data.length - 1], function(d) {
          return d.y0 + d.y;
        })
      ]);
      stream = this.svg.selectAll("g.stream").data(data);
      stream.enter().append("svg:g").attr("class", "stream");
      stream.style("fill", function(d) {
        return palette.color(d.transaction);
      });
      rect = stream.selectAll("rect.area").data(Object);
      rect.enter().append("svg:rect").attr("class", "area").attr("x", function(d) {
        return scale_x(d.x) + '%';
      }).attr("width", 100 / intervals + '%');
      return rect.attr("y", function(d) {
        return 100 - scale_y(d.y0 + d.y) + '%';
      }).attr("height", function(d) {
        return scale_y(d.y) + '%';
      });
    };

    return Histogram;

  })();

}).call(this);
